http:
  port: 3000
db:
  postgres:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: app
  mongo:
    host: localhost
    port: 27017
    username: mongo
    password: mongo
    database: app
jwt:
  secret: jwt-secret
  expiresIn: 60d
